ideal_width = 72
max_width   = 80

## disabled until it stops failing on URLs
# wrap_comments = true

## disabled until it stops reordering imports separated by an empty
## line
# reorder_imports        = true
reorder_imported_names = true

fn_arg_indent    = "Tabbed"
fn_args_layout   = "Block"
fn_args_density  = "CompressedIfEmpty"
fn_brace_style   = "PreferSameLine"

item_brace_style = "PreferSameLine"

use_try_shorthand = true

generics_ident    = "Tabbed"
where_pred_indent = "Tabbed"
